 image: node:latest

    stages:
      - build

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
        - node index.js
        
      artifacts:
        paths:
          - node_modules/
