language: node_js
node_js:
- stable

env:
  global:
    secure: FvuGHyjvsxbPvvFU9ol23p47iGo1TeCWu0b5NkL+p9l7hRbK+z0lU+ymzwS5jm6uq5CvwwHOb8prP/TtcyvGOuK/nEX7ndRqo4APa4EnxkDC7Ak7Dc5juNgj2xRFuWulMifDRZnyiC1OuyZYrM1Y7dnbrNbRfQjOIMbpER0Iphx2Pqm/wGYSC9EfULkLsif544vPSumhKfHC/kAQuhoBRa8yYHs8fzu96TrrQCYodJBPBxu8gwLSYtFAonY3djQ/xGENB6/b5GbirOxL5dEKWGIBGJ4kbH7gGWfORoxP4LhA0vOtvp/1tJI17h8Y0QmJ2zxH4CaZJL0+93QVNeyyaqrO+bBDXqNYeDr6tZc8Fg1bdM8WIbEKuqZTRt2+w/x3+mr6NMWCyEBXKIdYps1nqsYJcRCj4NG2LnsmCmpVBmxhrMNBAmyuQX94qlA+jNMVR+Nsa04jf/u+cURA7ZcKy0apBDexaGKLoGQJczfZGKrSuAuG8aGm5hg4RrheC6hlkaGm50MIIU3HjyCc+gtK2m8S9HlFapY+yFHWFi02puwfFTdv9adwLbTIEOHuTWgjkSMEbmJ6uQ3HsFEfyJgUznk4OnHt4+ANepr7CvC9l+nqiuUbxDFRUfbHgP57JiSl4xzWH8GSUfTK1eQJtjFVbuxsH0pJo40pt/SBhFGi61c=
script:
- node index.js

after_success:
  - .travis/push.sh